SELECT
        DEPARTMENT_NAME "학과 명"
       ,CATEGORY 계열
   FROM TB_DEPARTMENT;     
   
SELECT 
        DEPARTMENT_NAME || '의 정원은 ' || CAPACITY ||' 명 입니다.'
   FROM TB_DEPARTMENT;
   
SELECT
        DEPARTMENT_NAME
   FROM TB_DEPARTMENT
  WHERE DEPARTMENT_NAME = '국어국문학과';
  
SELECT
        STUDENT_NAME
   FROM TB_STUDENT
  WHERE STUDENT_SSN LIKE '_______2%'
    AND ABSENCE_YN = 'Y'
    AND DEPARTMENT_NO = 001;
    
SELECT
        STUDENT_NAME
   FROM TB_STUDENT
  WHERE STUDENT_NO IN ('A513119','A513090', 'A513110', 'A513091', 'A513079')
  ORDER BY STUDENT_NAME DESC;      
        
SELECT
        DEPARTMENT_NAME
       ,CATEGORY
   FROM TB_DEPARTMENT
  WHERE CAPACITY >= 20
    AND CAPACITY <= 30;

SELECT
        PROFESSOR_NAME
   FROM TB_PROFESSOR
  WHERE DEPARTMENT_NO IS NULL;

SELECT
        STUDENT_NAME
   FROM TB_STUDENT
  WHERE DEPARTMENT_NO IS NULL;
  
SELECT
        CLASS_NO
   FROM TB_CLASS
  WHERE PREATTENDING_CLASS_NO IS NOT NULL;
  
SELECT
        DISTINCT CATEGORY
   FROM TB_DEPARTMENT
  ORDER BY 1;
  
SELECT
        STUDENT_NO
       ,STUDENT_NAME
       ,STUDENT_SSN
   FROM TB_STUDENT
  WHERE ENTRANCE_DATE BETWEEN '02/01/01' and '02/12/31'
    AND STUDENT_ADDRESS LIKE '전주%'
    AND ABSENCE_YN = 'N'
  ORDER BY STUDENT_NAME ASC;
  
SELECT
        STUDENT_NO 학번
       ,STUDENT_NAME 이름
       ,ENTRANCE_DATE 입학년도
   FROM TB_STUDENT
  WHERE DEPARTMENT_NO = '002'
  ORDER BY ENTRANCE_DATE ASC;
  
SELECT
        PROFESSOR_NAME
       ,PROFESSOR_SSN
   FROM TB_PROFESSOR
  WHERE LENGTH(PROFESSOR_NAME) != 3;
  
SELECT
        PROFESSOR_NAME 교수이름
       ,FLOOR(MONTHS_BETWEEN(SYSDATE, TO_DATE('19'||SUBSTR(PROFESSOR_SSN, 1,6),'YYYYMMDD'))/12) 나이
   FROM TB_PROFESSOR
  WHERE SUBSTR(PROFESSOR_SSN, 8, 1) LIKE 1
  ORDER BY PROFESSOR_SSN DESC;
  
SELECT
        SUBSTR(PROFESSOR_NAME, 2) 이름
   FROM TB_PROFESSOR;
   
SELECT
        STUDENT_NO
       ,STUDENT_NAME
   FROM TB_STUDENT
  WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) - EXTRACT(YEAR FROM (TO_DATE(SUBSTR(STUDENT_SSN, 1,2), 'RR'))) > 19;
  
SELECT
        TO_CHAR(TO_DATE('20201225','YYYYMMDD'),'DAY')
    FROM DUAL;
    
SELECT
        TO_CHAR(TO_DATE('99/10/11','YY/MM/DD'), 'YYYY')
       ,TO_CHAR(TO_DATE('49/10/11','YY/MM/DD'), 'YYYY')
       ,TO_CHAR(TO_DATE('99/10/11','RR/MM/DD'),'RRRR')
       ,TO_CHAR(TO_DATE('49/10/11','RR/MM/DD'), 'RRRR')
   FROM DUAL;
   
SELECT
        STUDENT_NO
       ,STUDENT_NAME
   FROM TB_STUDENT
  WHERE STUDENT_NO NOT LIKE 'A%';
  
SELECT
        ROUND(AVG(POINT),1) 평점
   FROM TB_GRADE
  WHERE STUDENT_NO LIKE 'A517178';
  
SELECT
        DEPARTMENT_NO 학과번호
       ,COUNT(*) "학생수(명)"
    FROM TB_STUDENT
   GROUP BY DEPARTMENT_NO
   ORDER BY 1;

SELECT
        COUNT(*)
   FROM TB_STUDENT
  WHERE COACH_PROFESSOR_NO IS NULL;
  
SELECT
        SUBSTR(TERM_NO,1,4) 년도
       ,ROUND(AVG(POINT),1) "년도 별 평점"
   FROM TB_GRADE
  WHERE STUDENT_NO = 'A112113'
  GROUP BY SUBSTR(TERM_NO,1,4)
  ORDER BY 1;
  
SELECT
        DEPARTMENT_NO 학과코드명
       ,COUNT(DECODE(ABSENCE_YN, 'Y', 1)) "휴학생 수"
   FROM TB_STUDENT
  GROUP BY DEPARTMENT_NO
  ORDER BY 1;

SELECT
        STUDENT_NAME 동일이름
       ,COUNT(*) "동명인 수"
   FROM TB_STUDENT
   GROUP BY STUDENT_NAME
   HAVING COUNT(*) > 1;

SELECT DECODE(GROUPING(SUBSTR(TERM_NO,1,4)), 0,SUBSTR(TERM_NO,1,4), 1,' ') 년도, 
        DECODE(GROUPING(SUBSTR(TERM_NO,5,2)), 0,SUBSTR(TERM_NO,5,2), 1,' ') 학기, 
        ROUND(AVG(point),1) 평균
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4), SUBSTR(TERM_NO,5,2));

SELECT
        STUDENT_NAME "학생 이름"
       ,STUDENT_ADDRESS 주소지
   FROM TB_STUDENT
  ORDER BY STUDENT_NAME ASC;
  
SELECT
        STUDENT_NAME
       ,STUDENT_SSN
   FROM TB_STUDENT
  WHERE ABSENCE_YN = 'Y'
  ORDER BY FLOOR(MONTHS_BETWEEN(SYSDATE, TO_DATE('19'||SUBSTR(STUDENT_SSN, 1,6),'YYYYMMDD'))/12) ASC;
  
SELECT
        STUDENT_NAME 학생이름
       ,STUDENT_NO 학번
       ,STUDENT_ADDRESS "거주지 주소"
   FROM TB_STUDENT
  WHERE STUDENT_NO NOT LIKE 'A%'
    AND STUDENT_ADDRESS LIKE '경기도%'
     OR STUDENT_ADDRESS LIKE '강원도%'
  ORDER BY STUDENT_NAME ASC;
  
SELECT
        PROFESSOR_NAME
       ,PROFESSOR_SSN
   FROM TB_PROFESSOR
  WHERE DEPARTMENT_NO = '005'
 ORDER BY FLOOR(MONTHS_BETWEEN(SYSDATE, TO_DATE('19'||SUBSTR(PROFESSOR_SSN, 1,6),'YYYYMMDD'))/12) DESC;
 
SELECT
        STUDENT_NO
       ,POINT
   FROM TB_GRADE
  WHERE CLASS_NO = 'C3118100'
    AND TERM_NO = '200402'
  ORDER BY POINT DESC;
  
SELECT
        STUDENT_NO
       ,STUDENT_NAME
       ,DEPARTMENT_NAME
   FROM TB_STUDENT
   JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
  ORDER BY STUDENT_NAME ASC;

SELECT
        CLASS_NAME
       ,DEPARTMENT_NAME
   FROM TB_CLASS
   JOIN TB_DEPARTMENT USING(DEPARTMENT_NO);

SELECT
        CLASS_NAME
       ,PROFESSOR_NAME
    FROM TB_CLASS
    JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
    JOIN TB_PROFESSOR USING(PROFESSOR_NO);
    
SELECT
        CLASS_NAME
       ,PROFESSOR_NAME
    FROM TB_CLASS
    JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
    JOIN TB_PROFESSOR P USING(PROFESSOR_NO)
    JOIN TB_DEPARTMENT D ON(P.DEPARTMENT_NO = D.DEPARTMENT_NO)
   WHERE CATEGORY = '인문사회';

SELECT
        STUDENT_NO 학번
       ,STUDENT_NAME "학생 이름"
       ,ROUND(AVG(POINT), 1) "전체 평점"
   FROM TB_STUDENT
   JOIN TB_GRADE USING(STUDENT_NO)
   JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
  WHERE DEPARTMENT_NAME = '음악학과'
  GROUP BY STUDENT_NO, STUDENT_NAME
  ORDER BY STUDENT_NO;


SELECT
        DEPARTMENT_NAME 학과이름
       ,STUDENT_NAME 학생이름
       ,PROFESSOR_NAME 지도교수이름
   FROM TB_STUDENT
   JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
   JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
  WHERE STUDENT_NO = 'A313047';

SELECT
        STUDENT_NAME
       ,TERM_NO "TERM_NAME"
   FROM TB_STUDENT
   JOIN TB_GRADE USING (STUDENT_NO)
   JOIN TB_CLASS USING (CLASS_NO)
  WHERE CLASS_NAME = '인간관계론'
    AND TERM_NO LIKE '2007%';

SELECT
        CLASS_NAME
       ,DEPARTMENT_NAME
   FROM TB_CLASS
   JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
   LEFT JOIN TB_CLASS_PROFESSOR USING (CLASS_NO)
  WHERE CATEGORY LIKE '예체능'
    AND PROFESSOR_NO IS NULL;

SELECT
        STUDENT_NAME 학생이름
       ,NVL(PROFESSOR_NAME, '지도교수 미지정') 지도교수
   FROM TB_STUDENT
   JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
   LEFT JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
  WHERE DEPARTMENT_NAME = '서반아어학과'
  ORDER BY STUDENT_NO ASC;

-- 휴학생이 아닌 학생 중 평점 4.0이상
SELECT
        STUDENT_NO 학번
       ,STUDENT_NAME 이름
       ,DEPARTMENT_NAME "학과 이름"
       ,ROUND(AVG(POINT), 8) 평점
   FROM TB_STUDENT
   JOIN TB_GRADE USING (STUDENT_NO)
   JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
  WHERE ABSENCE_YN = 'N'
  GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
  HAVING ROUND(AVG(POINT),8) >= 4.0
  ORDER BY STUDENT_NAME;
  
  
SELECT
        CLASS_NO
       ,CLASS_NAME
       ,ROUND(AVG(POINT),8)
   FROM TB_GRADE
   JOIN TB_CLASS USING (CLASS_NO)
  WHERE DEPARTMENT_NO = '034'
    AND CLASS_TYPE LIKE '전공%'
  GROUP BY CLASS_NO, CLASS_NAME
  ORDER BY CLASS_NO;

--최경희 학생과 같은 과 학생의 이름과 주소
SELECT
        STUDENT_NAME
       ,STUDENT_ADDRESS
   FROM TB_STUDENT
   JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
  WHERE DEPARTMENT_NO = (
        SELECT DEPARTMENT_NO 
          FROM TB_STUDENT
         WHERE STUDENT_NAME = '최경희');

-- 국어국문학과에서 총 평점이 가장 높은 학생의 이름과 학번
SELECT
        STUDENT_NO
       ,STUDENT_NAME
   FROM (SELECT 
                STUDENT_NO
               ,STUDENT_NAME
           FROM TB_STUDENT
           JOIN TB_GRADE USING(STUDENT_NO)
           JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
          WHERE DEPARTMENT_NAME = '국어국문학과'
          GROUP BY STUDENT_NO, STUDENT_NAME
          ORDER BY AVG(POINT) DESC)
   WHERE ROWNUM = 1;
   
--환경조경학과가 속한 같은 계열 학과들의
--학과별 전공과목 평점
SELECT
        DEPARTMENT_NAME "계열 학과명"
       ,ROUND(AVG(POINT),1) 전공평점
   FROM TB_DEPARTMENT
   JOIN TB_CLASS USING(DEPARTMENT_NO)
   JOIN TB_GRADE USING (CLASS_NO)
  WHERE CATEGORY = (SELECT
                            CATEGORY
                       FROM TB_DEPARTMENT
                      WHERE DEPARTMENT_NAME = '환경조경학과')
    AND CLASS_TYPE LIKE '전공%'
  GROUP BY DEPARTMENT_NAME
  ORDER BY DEPARTMENT_NAME;
   
                

   
